### ISSUE TITLE
Vaccine - Logical Model / (Anne Nerenhausen - Riziv - INAMI)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#18]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Vaccine - Logical Model |  | cardinality of route : 1 .. 1 | Anne Nerenhausen - Riziv - INAMI |  |

**Comment by costateixeira** [comment]
Why is the route mandatory? are there case (e.g. report of previous immunization) where this is not known? Are there examples where route is irrelevant?

**Comment by costateixeira** [comment]
Discussed 25/9: Route remains optional for now. Later we can make mandatory with code "unknown" but this should start in the application, and only later in the interface
