### ISSUE TITLE
Vaccine - Logical Model / (Anne Nerenhausen - Riziv - INAMI)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#19]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Vaccine - Logical Model |  | cardinality of product : back to 0 .. 1 | Anne Nerenhausen - Riziv - INAMI |  |

**Comment by costateixeira** [comment]
Remains optional for now, we will still add "unknown" to the value set

**Comment by costateixeira** [comment]
Make those mandatory: product and route, add "unknown" as code
