### ISSUE TITLE
Vaccine - Logical Model / (Anne Nerenhausen - Riziv-INAMI)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#20]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Vaccine - Logical Model |  | Status must be Optional :  ..  | Anne Nerenhausen - Riziv-INAMI |  |

**Comment by costateixeira** [comment]
Discussed 25-09: Status OK to be mandatory
