### ISSUE TITLE
Vaccine : Logical Model / (Anne Nerenhausen - RIZIV _ INAMI)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#21]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Vaccine : Logical Model |  | How to do the link to Problem in case of reaction ? | Anne Nerenhausen - RIZIV _ INAMI |  |

This is via the reaction. Any formal capture of an adverse reaction will be via an independent AdverseEvent.

**Comment by costateixeira** [comment]
We cal link a vaccine to an observation or a note. The preferred flow is that the real reaction will be another Careset , corresponding to the fiche jaune. 
The flow is that the doctor / nurse simply captures remarks (nots or observations) while vaccinating, and at the end of the day they can query the server to see which vaccinations have a note and deserve a fiche jaune. 

Change to add some text to the narrative
