### ISSUE TITLE
HL7.BE.FHIR.RIZIV.SUMMARY\Addiction BE profile - FHIR v4.0.1 / Resource Profile: Addiction BE profile(Robin from the Platform)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#37]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| HL7.BE.FHIR.RIZIV.SUMMARY\Addiction BE profile - FHIR v4.0.1 | Resource Profile: Addiction BE profile | The model contains a .quantity. Is this expressed in the profile? | Robin from the Platform | robin.bosman@ehealth.fgov.be |  
This is indeed missing and should be added

**Comment by costateixeira** [comment]
Added "addiction quantifier" extension
