### ISSUE TITLE
HL7.BE.FHIR.RIZIV.SUMMARY\Location of the immunization event - FHIR v4.0.1 / Formal Views of Extension Content(Robin from the Platform)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#40]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| HL7.BE.FHIR.RIZIV.SUMMARY\Location of the immunization event - FHIR v4.0.1 | Formal Views of Extension Content | One of the options in this extension is to make a reference to a Location. But using immunization.location from the base resource it is also possible to make a reference to a Location. That could create ambiguity.
Proposal: remove reference to a Location in this extension? | Robin from the Platform | robin.bosman@ehealth.fgov.be |
This extension is to make the equivalent to a CodeableReference. Perhaps the best is to remove the original resource's Location element | José |
That would work as well I think.| Robin|

**Comment by RobinGroepT** [comment]
That would work as well I think.
