### ISSUE TITLE
HL7.FHIR.BE.RIZIV\Code System Laterality - FHIR v4.0.1 / CodeSystem: Code System Laterality(JCT)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#53]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| HL7.FHIR.BE.RIZIV\Code System Laterality - FHIR v4.0.1 | CodeSystem: Code System Laterality | Why is this code system needed? We can refer to SNOMED. Some of the codes are SNOMED , others are not | JCT |  |

**Comment by costateixeira** [comment]
Removed
