### ISSUE TITLE
HL7.FHIR.BE.RIZIV\Example - Patient Will - XML Representation - FHIR v4.0.1 / : Example - Patient Will - XML Representation(Robin from the Platform)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#70]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| HL7.FHIR.BE.RIZIV\Example - Patient Will - XML Representation - FHIR v4.0.1 | : Example - Patient Will - XML Representation | provision.code should be from required valueset | Robin from the Platform |  |

**Comment by costateixeira** [comment]
Given the last discussion, we should get the correct codes from the terminology team - so perhaps we need to update the valueset instead? The example already uses a SCT code, which is what we expect the valueset to contain.
