### ISSUE TITLE
HL7.FHIR.BE.RIZIV\Score Result Code system - FHIR v4.0.1 / CodeSystem: Score Result Code system(Robin from the platform)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#71]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| HL7.FHIR.BE.RIZIV\Score Result Code system - FHIR v4.0.1 | CodeSystem: Score Result Code system | Use of 'other' in valuesets: more a general remark for all valuesets: is it not more correct and logical to include the value 'OTH' from the codesystem https://terminology.hl7.org/1.0.0//CodeSystem-v3-NullFlavor.html ? | Robin from the platform |  |

**Comment by costateixeira** [comment]
Check administration route: I think it looks bad
http://build.fhir.org/ig/hl7-be/riziv-inami/branches/master/ValueSet-be-vs-vaccine-administration-route.html
