### ISSUE TITLE
HL7.FHIR.BE.RIZIV\Score Result Profile - FHIR v4.0.1 / Formal Views of Profile Content(Robin from the Platform)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#74]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| HL7.FHIR.BE.RIZIV\Score Result Profile - FHIR v4.0.1 | Formal Views of Profile Content | The current discriminator on category is not correct (error in QA) | Robin from the Platform |  |

**Comment by costateixeira** [comment]
Removed slicing - was unnecessary
