### ISSUE TITLE
HL7.FHIR.BE.RIZIV\Laterality extension - FHIR v4.0.1 / Formal Views of Extension Content(Robin from the Platform)

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/riziv-inami#75]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| HL7.FHIR.BE.RIZIV\Laterality extension - FHIR v4.0.1 | Formal Views of Extension Content | As this extension uses codes from a HL7 list that contains SNOMED-CT codes, it makes more sense the value[x]  would be CodeableConcept datatype instead of code datatype | Robin from the Platform |  |

**Comment by costateixeira** [comment]
or Coding because we don't want to support free text / multiple codings?

**Comment by RobinGroepT** [comment]
I forgot about that one, yes, indeed. Although I am not sure we should prevent free text here.

**Comment by costateixeira** [comment]
free text in laterality? that would mean things like "links" (which is OK), but also, "côté droit" (harder), or "légèrement antérieur"...

**Comment by RobinGroepT** [comment]
True, that might introduce some problems, let's try first with Coding.
